//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatermarkedTextBox {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WatermarkedTextBox.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string catAbout {
            get {
                return ResourceManager.GetString("catAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watermark.
        /// </summary>
        internal static string catWatermark {
            get {
                return ResourceManager.GetString("catWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information about the author..
        /// </summary>
        internal static string descAuthor {
            get {
                return ResourceManager.GetString("descAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to the git repository..
        /// </summary>
        internal static string descGit {
            get {
                return ResourceManager.GetString("descGit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push the WatermarkedTextBox in a mode where it can display multiple lines of text.
        /// </summary>
        internal static string descMultilineActionList {
            get {
                return ResourceManager.GetString("descMultilineActionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When this property is true, the WatermarkFont property use FontFamily and Size properties of the primary Font..
        /// </summary>
        internal static string descUsePrimaryFont {
            get {
                return ResourceManager.GetString("descUsePrimaryFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the value of the UsePrimaryFont property changes..
        /// </summary>
        internal static string descUsePrimaryFontChanged {
            get {
                return ResourceManager.GetString("descUsePrimaryFontChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The font used to display watermark in the control..
        /// </summary>
        internal static string descWatermarkFont {
            get {
                return ResourceManager.GetString("descWatermarkFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event raised when the value of the WatermarkFont property is changed on Control..
        /// </summary>
        internal static string descWatermarkFontChanged {
            get {
                return ResourceManager.GetString("descWatermarkFontChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The foreground color of this component, which is used to display watermark text. Value is ignore if this control has own text..
        /// </summary>
        internal static string descWatermarkForeColor {
            get {
                return ResourceManager.GetString("descWatermarkForeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event raised when the value of the WatermarkForeColor property is changed on Control..
        /// </summary>
        internal static string descWatermarkForeColorChanged {
            get {
                return ResourceManager.GetString("descWatermarkForeColorChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The watermark text associated with the control..
        /// </summary>
        internal static string descWatermarkText {
            get {
                return ResourceManager.GetString("descWatermarkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines the position of the text within the watermark..
        /// </summary>
        internal static string descWatermarkTextAlign {
            get {
                return ResourceManager.GetString("descWatermarkTextAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the value of the WatermarkTextAlign property changes..
        /// </summary>
        internal static string descWatermarkTextAlignChanged {
            get {
                return ResourceManager.GetString("descWatermarkTextAlignChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event raised when the value of the WatermarkText property is changed on Control..
        /// </summary>
        internal static string descWatermarkTextChanged {
            get {
                return ResourceManager.GetString("descWatermarkTextChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property with this name is not exist..
        /// </summary>
        internal static string propertyNullExceptionMessage {
            get {
                return ResourceManager.GetString("propertyNullExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string tabAbout {
            get {
                return ResourceManager.GetString("tabAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watermark.
        /// </summary>
        internal static string watermarkDefaultText {
            get {
                return ResourceManager.GetString("watermarkDefaultText", resourceCulture);
            }
        }
    }
}
